name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Se ejecuta cada 6 horas
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: NextiaSensei
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#FF006E&color_dots=#0d1117,#1a1b27,#6B46C1,#F70A8D,#00D4FF
            dist/github-contribution-grid-snake-dark.svg?color_snake=#00D4FF&color_dots=#161B22,#1f2937,#6B46C1,#F70A8D,#00D4FF
          
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
